language: objective-c

before_install:
  - cd sdk && pod install; cd ..
#  - curl -O http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock/1.52/wiremock-1.52-standalone.jar
#  - java -jar wiremock-1.52-standalone.jar --record-mappings --port 8080 --verbose --root-dir "test/core_tests/wiremock" &

script:
  - xctool -workspace sdk/all_services.xcworkspace -scheme outlook_services -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool -workspace sdk/all_services.xcworkspace -scheme files_services -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool -workspace sdk/all_services.xcworkspace -scheme discovery_services -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool -workspace sdk/all_services.xcworkspace -scheme directory_services -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool -workspace sdk/all_services.xcworkspace -scheme onenote_services -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool -workspace sdk/all_services.xcworkspace -scheme unified_services -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
#  - xctool test -workspace test/core_tests/core_tests.xcworkspace -scheme core_tests -sdk iphonesimulator

after_success:
#  - curl http://localhost:8080/__admin/shutdown
